image: php:7.1-alpine3.8

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apk get --no-cache unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - vendor/bin/phpunit
